Vagrant.configure(2) do |config|
  
  config.vm.define "master" do |master|
    master.vm.box = "rhel-7.1"
    master.vm.network "private_network", ip: "192.168.232.101"
    master.vm.provider "libvirt" do |libvirt|
      libvirt.driver = "kvm"
      libvirt.memory = 1024
      libvirt.cpus = 4
    end
  end

  config.vm.define "node1" do |node1|
    node1.vm.box = "rhel-7.1"
    node1.vm.network "private_network", ip: "192.168.232.201"
    node1.vm.provider "libvirt" do |libvirt|
      libvirt.driver = "kvm"
      libvirt.memory = 1024
      libvirt.cpus = 4
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.box = "rhel-7.1"
    node2.vm.network "private_network", ip: "192.168.232.202"
    node2.vm.provider "libvirt" do |libvirt|
      libvirt.driver = "kvm"
      libvirt.memory = 1024
      libvirt.cpus = 4
    end
  end

end
