Vagrant.configure(2) do |config|
  config.vm.box = "rhel-7.1"
  config.vm.network "private_network", ip: "192.168.233.101"
  config.vm.provider "libvirt" do |libvirt|
    libvirt.driver = "kvm"
    libvirt.memory = 4096
    libvirt.cpus = 4
  end
end
